### PR TITLE
CU-uta20e: fix cut-off screen on registration page on android chrome

### PR DESCRIPTION
**Pull request by jcook-ev**
Click-up ticket: https://app.clickup.com/t/uta20e

This solution delays the input field focus until page transition is over to avoid Chrome getting confused and cutting off the UI.

### CODE REVIEW

**Review by flavioruiz — APPROVED** [review]

**Comment by taylor1791** [comment]
Usually fixes that involve `setTimeout` are breeding grounds for race conditions. Additionally, it is unclear why this fixes the issue. If I knew why it fixed the issue, I may be a able to make a suggestion.

**Comment by bdehlin** [comment]
@taylor1791  I believe this fixes the issue because the keyboard pops up on android when an input field is focused so if the input field isn't focused until later the keyboard doesn't interrupt the page slide-in animation. I also agree that the race condition seems risky, this will still be broken for any users whose device/connection speed is really bad. I would guess there may also be weirdness if you are on a faster device and then try to immediately select a different input field as soon as the animation finishes (but perhaps not, this is a guess, at the very least it will probably appear a bit odd on faster devices). It seems to me like having the solution be based on the specific animation state we're waiting for on this page would be a safer solution but I don't know what that would be without digging into it a little

**Comment by taylor1791** [comment]
One idea is to make autofocus aware of animations and focus after the animation end event, but it isn't obvious to me how we would know to listen for the animation end event.

We could stop using the autofocus prop on the text-input and move it into a higher component. This will allow us to know to listen for an animation end event. I think this is my preference. What do you think @bdehlin and @jcook-ev

**Comment by jcook-ev** [comment]
I think that makes sense to me. I will look into it.

**Pull request closed without merging**
